## simple array

First and foremost is important to import numpy. 

Conda is an open-source BSD-licensed cross-platform package manager. It can easily install NumPy:
- [win command] choco install anaconda3

In [1]:
import numpy as np

#simple array
A = np.array(
    [
        [1, 2, 3],
        [3, 4, 5]
    ]
)

print(A)

[[1 2 3]
 [3 4 5]]


## array of float

In [2]:
#array of float
A = np.array(
    [
        [1.1, 2, 3],
        [3  , 4, 5]
    ]
)

print(A)

[[1.1 2.  3. ]
 [3.  4.  5. ]]


# array of complex number

In [3]:
A = np.array(
    [
        [1, 2, 3],
        [3, 4, 5]
    ], 
    dtype = complex
)

print(A)

[[1.+0.j 2.+0.j 3.+0.j]
 [3.+0.j 4.+0.j 5.+0.j]]


## array of zeros

In [4]:
A = np.zeros((2, 3))
print(A)

[[0. 0. 0.]
 [0. 0. 0.]]


## array of ones

In [5]:
A = np.ones((1,5), dtype=np.int32)
print(A)

[[1 1 1 1 1]]


## arange

In [6]:
A = np.arange(4)
print(A)

[0 1 2 3]


## shape

In [7]:
A = np.arange(24).reshape(6, 4)
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


## Addition of Two Matrices

In [8]:
A = np.array(
    [
        [2, 6], 
        [9, 3]
    ]
)

B = np.array(
    [
        [-4, 5],
        [6, -5]
    ]
)

C = A + B
print(C)


[[-2 11]
 [15 -2]]


## Multiplication of Two Matrices

In [9]:
A = np.array(
    [
        [3, 6, 9],
        [5, -3, 0]
    ]
)

B = np.array(
    [
        [1, 1],
        [2, 2],
        [3, -3]
    ]
)

C = A.dot(B)
print(C)

[[ 42 -12]
 [ -1  -1]]


## Transpose of a Matrix

In [10]:
A = np.array(
    [
        [1, 1],
        [2, 2],
        [3, -3]
    ]
)

B = A.transpose()

print('A =\n{0}'.format(A))
print('B =\n{0}'.format(B))



A =
[[ 1  1]
 [ 2  2]
 [ 3 -3]]
B =
[[ 1  2  3]
 [ 1  2 -3]]


## Access matrix elements

### simple access

In [11]:
A = np.array([2, 4, 6, 8, 10])

print('A[0]', A[0])
print('A[2]', A[2])
#reverse
print('A[-1]', A[-1])
print('A[-2]', A[-2])

A[0] 2
A[2] 6
A[-1] 10
A[-2] 8


### matrix access

In [12]:
A = np.array(
    [
        [1, 4, 5, 6],
        [4, -3, 4, 0],
        [-6, 7, 19, 11]
    ]
)

print('A[0][0]', A[0][0])
print('A[1][2]', A[1][2])

#get last
print('A[-1][-1]', A[-1][-1])

A[0][0] 1
A[1][2] 4
A[-1][-1] 11


### row access

In [13]:
#same matrix (just to make it visible)
A = np.array(
    [
        [1, 4, 5, 6],
        [4, -3, 4, 0],
        [-6, 7, 19, 11]
    ]
)

print('A[0]', A[0])
print('A[2]', A[2])
#get last row
print('A[-1]', A[-1])


A[0] [1 4 5 6]
A[2] [-6  7 19 11]
A[-1] [-6  7 19 11]


### column access

In [14]:
#same matrix (just to make it visible)
A = np.array(
    [
        [1, 4, 5, 6],
        [4, -3, 4, 0],
        [-6, 7, 19, 11]
    ]
)

print('A[:,0]', A[:,0])
print('A[:,2]', A[:,2])
print('A[:,-1]', A[:,-1])

A[:,0] [ 1  4 -6]
A[:,2] [ 5  4 19]
A[:,-1] [ 6  0 11]


## Slicing
Slicing of a one-dimensional NumPy array is similar to a list.

In [15]:
A = np.array([1, 3, 5, 7, 9, 7, 5])

print('3rd to 5th element: ', A[2:5])
print('1st to 4th element: ', A[:-5])
print('6th to last: ', A[5:])
print('all: ', A[:])
print('reversing list: ', A[::-1])


3rd to 5th element:  [5 7 9]
1st to 4th element:  [1 3]
6th to last:  [7 5]
all:  [1 3 5 7 9 7 5]
reversing list:  [5 7 9 7 5 3 1]


## Slicing Matrix

In [16]:
A = np.array(
    [
        [1, 4, 5, 6, 15],
        [4, -3, 4, 0, 21],
        [-6, 7, 19, 11, 17]
    ]
)

print('two rows, five comuns\n', A[:2, :5])
print('first row, all columns\n', A[:1])
print('all row, second columns\n', A[:, 2])
print('all row, third to fifth column\n', A[:, 2:5])

two rows, five comuns
 [[ 1  4  5  6 15]
 [ 4 -3  4  0 21]]
first row, all columns
 [[ 1  4  5  6 15]]
all row, second columns
 [ 5  4 19]
all row, third to fifth column
 [[ 5  6 15]
 [ 4  0 21]
 [19 11 17]]
